version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-python37-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-python37-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip3 install -r requirements.txt
    - save_cache:
        paths:
          - ./venv
        key: v1-python37-dependencies-{{ checksum "requirements.txt" }}
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: run tests
        command: |
          ./test.sh
    - store_artifacts:
        path: test-reports
        destination: test-reports

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: &installcf
          name: install cf-cli
          command: |
            sudo apt-get update
            sudo apt-get install wget gnupg2 apt-transport-https
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            sudo apt-get update
            sudo apt-get install cf-cli
            cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
            cf install-plugin blue-green-deploy -r CF-Community -f
      - run:
          name: deploy to cloud.gov
          command: |
            # If we do not specify a space, then deploy to the branch that we are on.
            # This lets you have dev/staging/master branches that automatically go to the right place.
            if [ -z "$CF_SPACE" ] ; then
              export CF_SPACE="$CIRCLE_BRANCH"
            fi
            if [ -z "$CF_ORG" ] ; then
              echo CF_ORG not set, aborting
              exit 1
            fi
            cf api https://api.fr.cloud.gov
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
            ./deploy-cloudgov.sh

  process_tasks:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          <<: *installcf
      - run:
          name: run process_tasks in the background
          command: |
            # If we do not specify a space, then deploy to the branch that we are on.
            # This lets you have dev/staging/master branches that automatically go to the right place.
            if [ -z "$CF_SPACE" ] ; then
              export CF_SPACE="$CIRCLE_BRANCH"
            fi
            if [ -z "$CF_ORG" ] ; then
              echo CF_ORG not set, aborting
              exit 1
            fi
            cf api https://api.fr.cloud.gov
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"

            cf run-task tanf "python manage.py process_tasks --duration=3540" --name process_tasks

workflows:
  version: 2
  hourly:
    jobs:
      - process_tasks
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - master
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              # Add more branches here if you want dev/staging/whatever environments
              only:
                - master
