# Generated by Django 2.2.4 on 2019-08-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='calendar_quarter',
            field=models.IntegerField(default=3, verbose_name='calendar quarter (header)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='calendar_year',
            field=models.IntegerField(default=2019, verbose_name='calendar year (header)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='state_code',
            field=models.CharField(default=None, max_length=3, verbose_name='state fips code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adult',
            name='tribe_code',
            field=models.CharField(default=None, max_length=3, verbose_name='tribe code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='calendar_quarter',
            field=models.IntegerField(default=3, verbose_name='calendar quarter (header)'),
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='calendar_year',
            field=models.IntegerField(default=2019, verbose_name='calendar year (header)'),
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='state_code',
            field=models.CharField(default=None, max_length=3, verbose_name='state fips code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='tribe_code',
            field=models.CharField(default='', max_length=3, verbose_name='tribe code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='calendar_quarter',
            field=models.IntegerField(default=3, verbose_name='calendar quarter (header)'),
        ),
        migrations.AddField(
            model_name='child',
            name='calendar_year',
            field=models.IntegerField(default=2019, verbose_name='calendar year (header)'),
        ),
        migrations.AddField(
            model_name='child',
            name='state_code',
            field=models.CharField(default=None, max_length=3, verbose_name='state fips code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='tribe_code',
            field=models.CharField(default=None, max_length=3, verbose_name='tribe code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedcase',
            name='calendar_quarter',
            field=models.IntegerField(default=3, verbose_name='calendar quarter (header)'),
        ),
        migrations.AddField(
            model_name='closedcase',
            name='calendar_year',
            field=models.IntegerField(default=2019, verbose_name='calendar year (header)'),
        ),
        migrations.AddField(
            model_name='closedcase',
            name='state_code',
            field=models.CharField(default=None, max_length=3, verbose_name='state fips code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedcase',
            name='tribe_code',
            field=models.CharField(default=None, max_length=3, verbose_name='tribe code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedperson',
            name='calendar_quarter',
            field=models.IntegerField(default=3, verbose_name='calendar quarter (header)'),
        ),
        migrations.AddField(
            model_name='closedperson',
            name='calendar_year',
            field=models.IntegerField(default=2019, verbose_name='calendar year (header)'),
        ),
        migrations.AddField(
            model_name='closedperson',
            name='state_code',
            field=models.CharField(default=None, max_length=3, verbose_name='state fips code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedperson',
            name='tribe_code',
            field=models.CharField(default=None, max_length=3, verbose_name='tribe code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiesbystratumdata',
            name='calendar_quarter',
            field=models.IntegerField(default=3, verbose_name='calendar quarter (header)'),
        ),
        migrations.AddField(
            model_name='familiesbystratumdata',
            name='calendar_year',
            field=models.IntegerField(default=2019, verbose_name='calendar year (header)'),
        ),
        migrations.AddField(
            model_name='familiesbystratumdata',
            name='state_code',
            field=models.CharField(default=None, max_length=3, verbose_name='state fips code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiesbystratumdata',
            name='tribe_code',
            field=models.CharField(default=None, max_length=3, verbose_name='tribe code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='calendar_quarter',
            field=models.IntegerField(default=3, verbose_name='calendar quarter (header)'),
        ),
        migrations.AddField(
            model_name='family',
            name='calendar_year',
            field=models.IntegerField(default=2019, verbose_name='calendar year (header)'),
        ),
        migrations.AddField(
            model_name='family',
            name='state_code',
            field=models.CharField(default=None, max_length=3, verbose_name='state fips code (header)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='tribe_code',
            field=models.CharField(default=None, max_length=3, verbose_name='tribe code (header)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='socialsecuritynumber',
            field=models.CharField(max_length=9, unique_for_date='reportingmonth', verbose_name='social security number (item 33)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='socialsecuritynumber',
            field=models.CharField(max_length=9, unique_for_date='reportingmonth', verbose_name='social security number (item 69)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='casenumber',
            field=models.CharField(max_length=11, unique_for_date='reportingmonth', verbose_name='case number (item 6)'),
        ),
    ]
