# Generated by Django 2.2.4 on 2019-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190827_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='socialsecuritynumber',
            field=models.CharField(max_length=9, verbose_name='social security number (item 33)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='socialsecuritynumber',
            field=models.CharField(max_length=9, verbose_name='social security number (item 69)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='casenumber',
            field=models.CharField(max_length=11, verbose_name='case number (item 6)'),
        ),
    ]
