# Generated by Django 2.2.4 on 2019-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190829_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='recordtype',
            field=models.CharField(default='', max_length=2, verbose_name='record type (T2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='recordtype',
            field=models.CharField(default='', max_length=2, verbose_name='record type (T6)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='recordtype',
            field=models.CharField(default='', max_length=2, verbose_name='record type (T3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedcase',
            name='recordtype',
            field=models.CharField(default='', max_length=2, verbose_name='record type (T4)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedperson',
            name='recordtype',
            field=models.CharField(default='', max_length=2, verbose_name='record type (T5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiesbystratumdata',
            name='recordtype',
            field=models.CharField(default='', max_length=2, verbose_name='record type (T7)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='recordtype',
            field=models.CharField(default='', max_length=2, verbose_name='record type (T1)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='reportingmonth',
            field=models.CharField(max_length=6, verbose_name='reporting month (item 4)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='reportingmonth',
            field=models.CharField(max_length=6, verbose_name='reporting month (item 4)'),
        ),
        migrations.AlterField(
            model_name='closedcase',
            name='reportingmonth',
            field=models.CharField(max_length=6, verbose_name='reporting month (item 4)'),
        ),
        migrations.AlterField(
            model_name='closedperson',
            name='reportingmonth',
            field=models.CharField(max_length=6, verbose_name='reporting month (item 4)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='reportingmonth',
            field=models.CharField(max_length=6, verbose_name='reporting month (item 4)'),
        ),
    ]
