# Generated by Django 2.2.4 on 2019-08-30 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190830_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='calendar_year',
        ),
        migrations.RemoveField(
            model_name='aggregateddata',
            name='calendar_year',
        ),
        migrations.RemoveField(
            model_name='child',
            name='calendar_year',
        ),
        migrations.RemoveField(
            model_name='closedcase',
            name='calendar_year',
        ),
        migrations.RemoveField(
            model_name='closedperson',
            name='calendar_year',
        ),
        migrations.RemoveField(
            model_name='familiesbystratumdata',
            name='calendar_year',
        ),
        migrations.RemoveField(
            model_name='family',
            name='calendar_year',
        ),
        migrations.AddField(
            model_name='adult',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time record was imported (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adult',
            name='imported_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='who record was imported by (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time record was imported (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='imported_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='who record was imported by (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time record was imported (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='imported_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='who record was imported by (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedcase',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time record was imported (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedcase',
            name='imported_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='who record was imported by (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedperson',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time record was imported (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedperson',
            name='imported_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='who record was imported by (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiesbystratumdata',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time record was imported (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiesbystratumdata',
            name='imported_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='who record was imported by (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time record was imported (metadata)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='imported_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='who record was imported by (metadata)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='calendar_quarter',
            field=models.IntegerField(verbose_name='calendar quarter (header)'),
        ),
        migrations.AlterField(
            model_name='aggregateddata',
            name='calendar_quarter',
            field=models.IntegerField(verbose_name='calendar quarter (header)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='calendar_quarter',
            field=models.IntegerField(verbose_name='calendar quarter (header)'),
        ),
        migrations.AlterField(
            model_name='closedcase',
            name='calendar_quarter',
            field=models.IntegerField(verbose_name='calendar quarter (header)'),
        ),
        migrations.AlterField(
            model_name='closedperson',
            name='calendar_quarter',
            field=models.IntegerField(verbose_name='calendar quarter (header)'),
        ),
        migrations.AlterField(
            model_name='familiesbystratumdata',
            name='calendar_quarter',
            field=models.IntegerField(verbose_name='calendar quarter (header)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='calendar_quarter',
            field=models.IntegerField(verbose_name='calendar quarter (header)'),
        ),
    ]
