# Generated by Django 2.2.4 on 2019-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20190916_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='dateofbirth',
            new_name='dateofbirth_1',
        ),
        migrations.RemoveField(
            model_name='child',
            name='familyafilliation',
        ),
        migrations.RemoveField(
            model_name='child',
            name='racehispanic',
        ),
        migrations.RemoveField(
            model_name='child',
            name='racenativeamerican',
        ),
        migrations.RemoveField(
            model_name='child',
            name='socialsecuritynumber',
        ),
        migrations.AddField(
            model_name='adult',
            name='citizenship',
            field=models.CharField(default='', max_length=1, verbose_name='citizenship/alienage (item 42)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='communitysvcexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: excused absences (item 56b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='communitysvcholidays',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: holidays (item 56c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='communitysvchours',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: hours of participation (item 56a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='coopwithchildsupport',
            field=models.CharField(default='', max_length=1, verbose_name='cooperation with child support (item 43)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='corehoursforoverallrate',
            field=models.CharField(default='', max_length=2, verbose_name='number of deemed core hours for overall rate (item 63)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='corehoursfortwoparentrate',
            field=models.CharField(default='', max_length=2, verbose_name='number of deemed core hours for the two-parent rate (item 64)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='countablemonths',
            field=models.IntegerField(default=0, verbose_name='number of countable months toward federal time limit (item 44)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='countablemonthsremaining',
            field=models.IntegerField(default=0, verbose_name='number of countable months remaining under state/tribe limit (item 45)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='currentmonthexempt',
            field=models.CharField(default='', max_length=1, verbose_name='current month exempt from state tirbe time-limit (item 46)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='earnedincome',
            field=models.IntegerField(default=0, verbose_name='amount of earned income (item 65)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='educationlevel',
            field=models.CharField(default='', max_length=12, verbose_name='education level (item 41)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='eduwithnodiplomaexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: excused absences (item 59b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='eduwithnodiplomaholidays',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: holidays (item 59c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='eduwithnodiplomahours',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: hours of participation (item 59a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='employmentstatus',
            field=models.CharField(default='', max_length=1, verbose_name='employment status (item 47)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='gender',
            field=models.IntegerField(default=0, verbose_name='gender (item 35)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='jobsearchexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: excused absences (item 55b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='jobsearchholidays',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: holidays (item 55c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='jobsearchhours',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: hours of participation (item 55a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='jobskillsexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: excused absences (item 58b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='jobskillsholidays',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: holidays (item 58c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='jobskillshours',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: hours of participation (item 58a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='maritalstatus',
            field=models.CharField(default='', max_length=1, verbose_name='marital status (item 37)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='nonssabenefits',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: receives benefits based on federal disability status under non-ssa programs (item 36b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='oasdibenefits',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: received federal disability insurance benefits under the oasdi program (item 36a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='onthejobtraining',
            field=models.CharField(default='', max_length=2, verbose_name='on the job training (item 54)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='otherwork',
            field=models.CharField(default='', max_length=2, verbose_name='other work activities (item 62)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='parentminorchild',
            field=models.CharField(default='', max_length=1, verbose_name='parent with minor child in the family (item 39)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='pregnantneeds',
            field=models.CharField(default='', max_length=11, verbose_name='needs of a pregnant woman (item 40)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='providingchildcareexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: excused absences (item 61b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='providingchildcareholidays',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: holidays (item 61c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='providingchildcarehours',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: hours of participation (item 61a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='raceasian',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: asian (item 34c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='raceblack',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: black or african american islander (item 34d)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='racewhite',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: white (item 34f)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='relationshiptohh',
            field=models.IntegerField(default=0, verbose_name='relationship to head of household (item 38)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='satisfactoryschoolexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: excused absences (item 60b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='satisfactoryschoolholidays',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: holidays (item 60c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='satisfactoryschoolhours',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: hours of participation (item 60a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='subsidizedprivateemployment',
            field=models.CharField(default='', max_length=2, verbose_name='subsidized private employment (item 51)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='subsidizedpublicemployment',
            field=models.CharField(default='', max_length=2, verbose_name='subsidized public employment (item 52)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='titlexivapdtbenefits',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: received aid to the permanently and totally disabled under title xiv-apdt (item 36c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='titlexviaabdbenefits',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: received aid to the aged, blind, and disabled under title xvi-aabd (item 36d)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='titlexvissibenefits',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: received ssi under title xvi-ssi (item 36e)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='unearnedincomeincometaxcredit',
            field=models.CharField(default='', max_length=2, verbose_name='amount of unearned income: earned income tax credit (item 66a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='unearnedincomeother',
            field=models.CharField(default='', max_length=2, verbose_name='amount of unearned income: other unearned income (item 66e)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='unearnedincomesocialsecurity',
            field=models.CharField(default='', max_length=2, verbose_name='amount of unearned income: social security (item 66b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='unearnedincomessi',
            field=models.CharField(default='', max_length=2, verbose_name='amount of unearned income: SSI (item 66c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='unearnedincomeworkerscomp',
            field=models.CharField(default='', max_length=2, verbose_name='amount of unearned income: workers compensation (item 66d)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='unsubsidizedemployment',
            field=models.CharField(default='', max_length=2, verbose_name='unsubsidized employment (item 50)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='vocationaltrainingexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: excused absences (item 57b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='vocationaltrainingholidays',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: holidays (item 57c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='vocationaltraininghours',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: hours of participation (item 57a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='workeligibleindicator',
            field=models.CharField(default='', max_length=2, verbose_name='work eligible individual indicator (item 48)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='workexperienceexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='work experience: excused absences (item 53b)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='workexperienceholidays',
            field=models.CharField(default='', max_length=2, verbose_name='work experience: holidays (item 53c)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='workexperiencehours',
            field=models.CharField(default='', max_length=2, verbose_name='work experience: hours of participation (item 53a)'),
        ),
        migrations.AddField(
            model_name='adult',
            name='workparticipationstatus',
            field=models.CharField(default='', max_length=2, verbose_name='work participation status (item 49)'),
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='firstmonthassist',
            field=models.IntegerField(default=0, verbose_name='total amount of assistance: first month (item 7)'),
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='secondmonthassist',
            field=models.IntegerField(default=0, verbose_name='total amount of assistance: second month (item 7)'),
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='thirdmonthassist',
            field=models.IntegerField(default=0, verbose_name='total amount of assistance: third month (item 7)'),
        ),
        migrations.AddField(
            model_name='child',
            name='citizenship_1',
            field=models.CharField(default='', max_length=1, verbose_name='citizenship/alienage (item 76)'),
        ),
        migrations.AddField(
            model_name='child',
            name='citizenship_2',
            field=models.CharField(default='', max_length=1, verbose_name='citizenship/alienage (item 76)'),
        ),
        migrations.AddField(
            model_name='child',
            name='communitysvcexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: excused absences (item 56b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='communitysvcholidays',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: holidays (item 56c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='communitysvchours',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: hours of participation (item 56a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='corehoursforoverallrate',
            field=models.CharField(default='', max_length=2, verbose_name='number of deemed core hours for overall rate (item 63)'),
        ),
        migrations.AddField(
            model_name='child',
            name='corehoursfortwoparentrate',
            field=models.CharField(default='', max_length=2, verbose_name='number of deemed core hours for the two-parent rate (item 64)'),
        ),
        migrations.AddField(
            model_name='child',
            name='dateofbirth_2',
            field=models.DateField(default='2019-08-30', verbose_name='date of birth (item 68)'),
        ),
        migrations.AddField(
            model_name='child',
            name='earnedincome',
            field=models.CharField(default='', max_length=4, verbose_name='amount of earned income (item 65)'),
        ),
        migrations.AddField(
            model_name='child',
            name='educationlevel_1',
            field=models.CharField(default='', max_length=12, verbose_name='education level (item 75)'),
        ),
        migrations.AddField(
            model_name='child',
            name='educationlevel_2',
            field=models.CharField(default='', max_length=12, verbose_name='education level (item 75)'),
        ),
        migrations.AddField(
            model_name='child',
            name='eduwithnodiplomaexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: excused absences (item 59b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='eduwithnodiplomaholidays',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: holidays (item 59c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='eduwithnodiplomahours',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: hours of participation (item 59a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='familyafilliation_1',
            field=models.IntegerField(default=0, verbose_name='family affiliation1: Child 1,3,5,7,9 (item 67)'),
        ),
        migrations.AddField(
            model_name='child',
            name='familyafilliation_2',
            field=models.IntegerField(default=0, verbose_name='family affiliation 2: Child 2,4,6,8,10 (item 67)'),
        ),
        migrations.AddField(
            model_name='child',
            name='gender_1',
            field=models.IntegerField(default=0, verbose_name='gender (item 71)'),
        ),
        migrations.AddField(
            model_name='child',
            name='gender_2',
            field=models.IntegerField(default=0, verbose_name='gender (item 71)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobsearchexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: excused absences (item 55b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobsearchholidays',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: holidays (item 55c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobsearchhours',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: hours of participation (item 55a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobskillsexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: excused absences (item 58b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobskillsholidays',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: holidays (item 58c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobskillshours',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: hours of participation (item 58a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='nonssabenefits_1',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: receives benefits based on federal disability status under non-ssa programs (item 72a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='nonssabenefits_2',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: receives benefits based on federal disability status under non-ssa programs (item 72a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='otherwork',
            field=models.CharField(default='', max_length=2, verbose_name='other work activities (item 62)'),
        ),
        migrations.AddField(
            model_name='child',
            name='parentminorchild_1',
            field=models.CharField(default='', max_length=1, verbose_name='parent with minor child in the family (item 74)'),
        ),
        migrations.AddField(
            model_name='child',
            name='parentminorchild_2',
            field=models.CharField(default='', max_length=1, verbose_name='parent with minor child in the family (item 74)'),
        ),
        migrations.AddField(
            model_name='child',
            name='providingchildcareexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: excused absences (item 61b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='providingchildcareholidays',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: holidays (item 61c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='providingchildcarehours',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: hours of participation (item 61a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='raceasian_1',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: asian (item 70c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='raceasian_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: asian (item 70c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='raceblack_1',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: black or african american islander (item 70d)'),
        ),
        migrations.AddField(
            model_name='child',
            name='raceblack_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: black or african american islander (item 70d)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racehispanic_1',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: hispanic or latino (item 70a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racehispanic_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: hispanic or latino (item 70a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racenativeamerican_1',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: american indian or alaska native (item 70b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racenativeamerican_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: american indian or alaska native (item 70b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racepacific_1',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: native hawaiian or other pacific islander (item 70e)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racepacific_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: native hawaiian or other pacific islander (item 70e)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racewhite_1',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: white (item 70f)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racewhite_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: white (item 70f)'),
        ),
        migrations.AddField(
            model_name='child',
            name='relationshiptohh_1',
            field=models.IntegerField(default=0, verbose_name='relationship to head of household (item 73)'),
        ),
        migrations.AddField(
            model_name='child',
            name='relationshiptohh_2',
            field=models.IntegerField(default=0, verbose_name='relationship to head of household (item 73)'),
        ),
        migrations.AddField(
            model_name='child',
            name='satisfactoryschoolexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: excused absences (item 60b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='satisfactoryschoolholidays',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: holidays (item 60c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='satisfactoryschoolhours',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: hours of participation (item 60a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='socialsecuritynumber_1',
            field=models.CharField(default='', max_length=9, verbose_name='social security number (item 69)'),
        ),
        migrations.AddField(
            model_name='child',
            name='socialsecuritynumber_2',
            field=models.CharField(default='', max_length=9, verbose_name='social security number (item 69)'),
        ),
        migrations.AddField(
            model_name='child',
            name='titlexvissibenefits_1',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: received ssi under title xvi-ssi (item 72b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='titlexvissibenefits_2',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: received ssi under title xvi-ssi (item 72b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeincometaxcredit',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: earned income tax credit (item 66a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeother',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: other unearned income (item 66e)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeother_1',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: other unearned income (item 77b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeother_2',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: other unearned income (item 77b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomesocialsecurity',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: social security (item 66b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomessi',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: SSI (item 66c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomessi_1',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: SSI (item 77a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomessi_2',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: SSI (item 77a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeworkerscomp',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: workers compensation (item 66d)'),
        ),
        migrations.AddField(
            model_name='child',
            name='vocationaltrainingexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: excused absences (item 57b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='vocationaltrainingholidays',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: holidays (item 57c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='vocationaltraininghours',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: hours of participation (item 57a)'),
        ),
    ]
