# Generated by Django 2.2.4 on 2019-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20190917_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='dateofbirth_2',
            field=models.DateField(verbose_name='date of birth (item 68)'),
        ),
    ]
