# Generated by Django 2.2.6 on 2019-11-16 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_auto_20190918_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='citizenship_2',
            field=models.CharField(default='', max_length=1, verbose_name='citizenship/alienage (item 76)'),
        ),
        migrations.AddField(
            model_name='child',
            name='communitysvcexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: excused absences (item 56b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='communitysvcholidays',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: holidays (item 56c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='communitysvchours',
            field=models.CharField(default='', max_length=2, verbose_name='community svs prog: hours of participation (item 56a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='corehoursforoverallrate',
            field=models.CharField(default='', max_length=2, verbose_name='number of deemed core hours for overall rate (item 63)'),
        ),
        migrations.AddField(
            model_name='child',
            name='corehoursfortwoparentrate',
            field=models.CharField(default='', max_length=2, verbose_name='number of deemed core hours for the two-parent rate (item 64)'),
        ),
        migrations.AddField(
            model_name='child',
            name='dateofbirth_2',
            field=models.DateField(default=datetime.date.today, verbose_name='date of birth (item 68)'),
        ),
        migrations.AddField(
            model_name='child',
            name='earnedincome',
            field=models.CharField(default='', max_length=4, verbose_name='amount of earned income (item 65)'),
        ),
        migrations.AddField(
            model_name='child',
            name='educationlevel_2',
            field=models.CharField(default='', max_length=12, verbose_name='education level (item 75)'),
        ),
        migrations.AddField(
            model_name='child',
            name='eduwithnodiplomaexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: excused absences (item 59b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='eduwithnodiplomaholidays',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: holidays (item 59c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='eduwithnodiplomahours',
            field=models.CharField(default='', max_length=2, verbose_name='education related to employment with no high school diploma: hours of participation (item 59a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='familyafilliation_2',
            field=models.IntegerField(default=0, verbose_name='family affiliation 2: Child 2,4,6,8,10 (item 67)'),
        ),
        migrations.AddField(
            model_name='child',
            name='gender_2',
            field=models.IntegerField(default=0, verbose_name='gender (item 71)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobsearchexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: excused absences (item 55b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobsearchholidays',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: holidays (item 55c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobsearchhours',
            field=models.CharField(default='', max_length=2, verbose_name='job search & job readiness: hours of participation (item 55a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobskillsexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: excused absences (item 58b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobskillsholidays',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: holidays (item 58c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='jobskillshours',
            field=models.CharField(default='', max_length=2, verbose_name='job skills training employment related: hours of participation (item 58a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='nonssabenefits_2',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: receives benefits based on federal disability status under non-ssa programs (item 72a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='otherwork',
            field=models.CharField(default='', max_length=2, verbose_name='other work activities (item 62)'),
        ),
        migrations.AddField(
            model_name='child',
            name='parentminorchild_2',
            field=models.CharField(default='', max_length=1, verbose_name='parent with minor child in the family (item 74)'),
        ),
        migrations.AddField(
            model_name='child',
            name='providingchildcareexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: excused absences (item 61b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='providingchildcareholidays',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: holidays (item 61c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='providingchildcarehours',
            field=models.CharField(default='', max_length=2, verbose_name='providing child care: hours of participation (item 61a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='raceasian_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: asian (item 70c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='raceblack_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: black or african american islander (item 70d)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racehispanic_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: hispanic or latino (item 70a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racenativeamerican_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: american indian or alaska native (item 70b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racepacific_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: native hawaiian or other pacific islander (item 70e)'),
        ),
        migrations.AddField(
            model_name='child',
            name='racewhite_2',
            field=models.CharField(default='', max_length=1, verbose_name='race/ethnicity: white (item 70f)'),
        ),
        migrations.AddField(
            model_name='child',
            name='relationshiptohh_2',
            field=models.IntegerField(default=0, verbose_name='relationship to head of household (item 73)'),
        ),
        migrations.AddField(
            model_name='child',
            name='satisfactoryschoolexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: excused absences (item 60b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='satisfactoryschoolholidays',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: holidays (item 60c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='satisfactoryschoolhours',
            field=models.CharField(default='', max_length=2, verbose_name='satisfactory school attendance: hours of participation (item 60a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='socialsecuritynumber_2',
            field=models.CharField(default='', max_length=9, verbose_name='social security number (item 69)'),
        ),
        migrations.AddField(
            model_name='child',
            name='titlexvissibenefits_2',
            field=models.CharField(default='', max_length=1, verbose_name='receives disability benefits: received ssi under title xvi-ssi (item 72b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeincometaxcredit',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: earned income tax credit (item 66a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeother',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: other unearned income (item 66e)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeother_2',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: other unearned income (item 77b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomesocialsecurity',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: social security (item 66b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomessi',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: SSI (item 66c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomessi_2',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: SSI (item 77a)'),
        ),
        migrations.AddField(
            model_name='child',
            name='unearnedincomeworkerscomp',
            field=models.CharField(default='', max_length=4, verbose_name='amount of unearned income: workers compensation (item 66d)'),
        ),
        migrations.AddField(
            model_name='child',
            name='vocationaltrainingexcusedabsences',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: excused absences (item 57b)'),
        ),
        migrations.AddField(
            model_name='child',
            name='vocationaltrainingholidays',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: holidays (item 57c)'),
        ),
        migrations.AddField(
            model_name='child',
            name='vocationaltraininghours',
            field=models.CharField(default='', max_length=2, verbose_name='vocational education training: hours of participation (item 57a)'),
        ),
    ]
